language: cpp
matrix:
  include:
    - compiler: gcc
      env:
        CFLAGS="-Wall -Wextra -Wsign-compare -Wno-long-long -Wno-unused-parameter -pedantic"
        CXXFLAGS="-Woverloaded-virtual $CFLAGS"
    - compiler: clang
      env:
        CFLAGS="-Wall -Wextra -Wsign-compare -Wno-long-long -Wno-unused-parameter -pedantic -fcolor-diagnostics"
        CXXFLAGS="-Woverloaded-virtual $CFLAGS"
before_install:
 - sudo add-apt-repository -y ppa:george-edison55/cmake-precise
 - sudo add-apt-repository -y ppa:beineri/opt-qt54
 - sudo apt-get update -qq
 - sudo apt-get install -qq valac uuid-dev libevent-dev re2c libjansson-dev cmake libqt4-dev
 - sudo apt-get install -qq qt54base qt54translations qt54tools
 - git clone --depth=1 --branch=master git://github.com/haiwen/libsearpc.git deps/libsearpc
 - git clone --depth=1 --branch=master git://github.com/haiwen/ccnet.git deps/ccnet
 - git clone --depth=1 --branch=master git://github.com/haiwen/seafile.git deps/seafile
 # build libsearpc
 - cd deps/libsearpc && ./autogen.sh && ./configure
 - make -j8 && sudo make install && cd ../..
 # build ccnet
 - cd deps/ccnet && ./autogen.sh && ./configure --enable-client --disable-server
 - make -j8 && sudo make install && cd ../..
 # build seafile
 - cd deps/seafile && ./autogen.sh && ./configure --disable-fuse --disable-server --enable-client
 - make -j8 && sudo make install && cd ../..
script:
 - cmake -DBUILD_TESTING=on .
 - make -j8
 - make test
 - git clean -xfd
 - source /opt/qt54/bin/qt54-env.sh
 - cmake . -DBUILD_TESTING=on -DUSE_QT5=ON
 - make -j8
 - make test
notifications:
  email:
    recipients:
      - linshuai2012@gmail.com
      - rwindz0@gmail.com
