language: cpp
env:
  global:
   - secure: "VGKP/MgL+kk+DToAlMyZCN6id17oydM69yR8RC0jI9RKM73Jgsyb5iRUbP3UOpqhl/dZQB5dt14I8HMneyy7lskd+l5RNMrh5yPxM4/D9PrRhwte9xZhrDXoAi79GyRDidNhyt6g6rM3uViPe/K41c9qJy3ZY4P/t/uMq5hFKfs="
matrix:
  include:
    - compiler: gcc
      env:
        CFLAGS="-Wall -Wextra -Wsign-compare -Wno-long-long -Wno-unused-parameter -pedantic"
        CXXFLAGS="-Woverloaded-virtual $CFLAGS"
    - compiler: clang
      env:
        CFLAGS="-Wall -Wextra -Wsign-compare -Wno-long-long -Wno-unused-parameter -pedantic -fcolor-diagnostics"
        CXXFLAGS="-Woverloaded-virtual $CFLAGS"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq valac uuid-dev libevent-dev libarchive-dev re2c libjansson-dev libqt4-dev
 - git clone --depth=1 --branch=master git://github.com/haiwen/libsearpc.git deps/libsearpc
 - git clone --depth=1 --branch=master git://github.com/haiwen/ccnet.git deps/ccnet
 - git clone --depth=1 --branch=master git://github.com/haiwen/seafile.git deps/seafile
 # build libsearpc
 - cd deps/libsearpc && ./autogen.sh && ./configure
 - make -j8 && sudo make install && cd ../..
 # build ccnet
 - cd deps/ccnet && ./autogen.sh && ./configure --enable-client --disable-server
 - make -j8 && sudo make install && cd ../..
 # build seafile
 - cd deps/seafile && ./autogen.sh && ./configure --disable-fuse --disable-server --enable-client
 - make -j8 && sudo make install && cd ../..
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cmake -DBUILD_TESTING=on . ; make clean ; make -j8 ; make test ; fi
addons:
  coverity_scan:
    project:
      name: "haiwen/seafile-client"
      description: "Build submitted via Travis CI"
    notification_email: rwindz0@gmail.com
    build_command_prepend: "cmake .; make clean"
    build_command:   "make -j 8"
    branch_pattern: coverity_scan
notifications:
  email:
    recipients:
      - linshuai2012@gmail.com
